# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_result', models.CharField(max_length=50, verbose_name='Результат тестирования')),
                ('asset_text_result', models.TextField(verbose_name='Подробный результат тестирования')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.CharField(max_length=50, verbose_name='Описание вопроса')),
                ('question_text', models.TextField(verbose_name='Формулировка вопроса')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_question',
            field=models.ManyToManyField(to='Assets.Question'),
        ),
    ]
